steps:
  # Build backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', './backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Build and deploy frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'

  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting']
    dir: 'frontend'

images:
  - 'gcr.io/$PROJECT_ID/backend' 