services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anmol1270
      POSTGRES_DB: ai_blog_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:anmol1270@db:5432/ai_blog_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anmol1270
      - POSTGRES_DB=ai_blog_assistant
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install -e . &&
             python -m alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 