version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anmol1270
      POSTGRES_DB: ai_blog_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:anmol1270@db:5432/ai_blog_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anmol1270
      - POSTGRES_DB=ai_blog_assistant
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PYTHONPATH=/app
    depends_on:
      - db
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 