"""update keywords to json

Revision ID: cda7caaffa60
Revises: a1308b03e3cc
Create Date: 2024-04-01 05:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cda7caaffa60'
down_revision: Union[str, None] = 'a1308b03e3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE blog_posts ALTER COLUMN keywords TYPE JSON USING CASE WHEN keywords IS NULL THEN NULL ELSE keywords::json END')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE blog_posts ALTER COLUMN keywords TYPE VARCHAR USING CASE WHEN keywords IS NULL THEN NULL ELSE keywords::text END')
    # ### end Alembic commands ###
