"""add wordpress settings to users

Revision ID: df346b338a7b
Revises: cda7caaffa60
Create Date: 2024-03-21 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df346b338a7b'
down_revision: Union[str, None] = 'cda7caaffa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wordpress_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wordpress_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wordpress_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wordpress_password')
    op.drop_column('users', 'wordpress_username')
    op.drop_column('users', 'wordpress_url')
    # ### end Alembic commands ###
